language: python
python:
  - 2.7
  - 3.5

install:
  - pip install codecov

script:
  - mkdir ~/rust-installer
  - curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh -y
  - source $HOME/.cargo/env
  - cargo build
  - cp target/debug/libhermes_mqtt_ffi.so platforms/hermes-python/hermes_python/dylib
  - mkdir platforms/hermes-python/tests/roundtrip/debug
  - cp target/debug/libhermes_ffi_test.so platforms/hermes-python/tests/roundtrip/debug
  - cd platforms/hermes-python
  - pip install -r requirements/tests.txt
  - python setup.py test

after_success:
  - codecov
