language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install codecov

script:
  - curl https://sh.rustup.rs -sSf | sh
  - cargo build
  - cp target/debug/libhermes_ffi.so platforms/hermes-python/hermes_python/dylib
  - mkdir platforms/hermes-python/tests/roundtrip/debug
  - cp target/debug/libhermes_ffi_test.so platforms/hermes-python/tests/roundtrip/debug
  - cd platforms/hermes-python
  - pip install -r requirements/test
  - python setup.py test

after_success:
  - codecov